package exo1;

import org.json.JSONObject;

/**
 * Formats contact information as a Json file.
 * Generated by AI.
 */
public class JsonFormatter implements ContactFormatter {
    @Override
    public String formatContact(Contact contact) {
        JSONObject json = new JSONObject();
        json.put("name", contact.getName());
        json.put("phoneNumber", contact.getPhoneNumber());

        if (contact.getFirstName() != null) {
            json.put("firstName", contact.getFirstName());
        }
        if (contact.getEmail() != null) {
            json.put("email", contact.getEmail());
        }
        if (contact.getWorkplace() != null) {
            json.put("workplace", contact.getWorkplace());
        }
        if (contact.getCity() != null) {
            json.put("city", contact.getCity());
        }
        if (contact.getState() != null) {
            json.put("state", contact.getState());
        }
        if (contact.getBirthday() != null) {
            json.put("birthday", contact.getBirthday());
        }

        return json.toString(4); // Pretty-print JSON with 4-space indentation
    }
}
