package exo1;

/**
 * Formats contact information as a String.
 * Generated by AI.
 */
public class TextFormatter implements ContactFormatter {
    @Override
    public String formatContact(Contact contact) {
        StringBuilder formatted = new StringBuilder();
        formatted.append("Name: ").append(contact.getName())
                .append(", Phone number: ").append(contact.getPhoneNumber());

        if (contact.getFirstName() != null) {
            formatted.append(", First Name: ").append(contact.getFirstName());
        }
        if (contact.getEmail() != null) {
            formatted.append(", Email: ").append(contact.getEmail());
        }
        if (contact.getWorkplace() != null) {
            formatted.append(", Workplace: ").append(contact.getWorkplace());
        }
        if (contact.getCity() != null) {
            formatted.append(", City: ").append(contact.getCity());
        }
        if (contact.getState() != null) {
            formatted.append(", State: ").append(contact.getState());
        }
        if (contact.getBirthday() != null) {
            formatted.append(", Birthday: ").append(contact.getBirthday());
        }

        return formatted.toString();
    }
}