package exo1;

/**
 * Formats contact information as a Xml file.
 * Generated by AI.
 */
public class XmlFormatter implements ContactFormatter {
    @Override
    public String formatContact(Contact contact) {
        StringBuilder xml = new StringBuilder();
        xml.append("<contact>\n")
                .append("  <name>").append(contact.getName()).append("</name>\n")
                .append("  <phoneNumber>").append(contact.getPhoneNumber()).append("</phoneNumber>\n");

        if (contact.getFirstName() != null) {
            xml.append("  <firstName>").append(contact.getFirstName()).append("</firstName>\n");
        }
        if (contact.getEmail() != null) {
            xml.append("  <email>").append(contact.getEmail()).append("</email>\n");
        }
        if (contact.getWorkplace() != null) {
            xml.append("  <workplace>").append(contact.getWorkplace()).append("</workplace>\n");
        }
        if (contact.getCity() != null) {
            xml.append("  <city>").append(contact.getCity()).append("</city>\n");
        }
        if (contact.getState() != null) {
            xml.append("  <state>").append(contact.getState()).append("</state>\n");
        }
        if (contact.getBirthday() != null) {
            xml.append("  <birthday>").append(contact.getBirthday()).append("</birthday>\n");
        }

        xml.append("</contact>");
        return xml.toString();
    }
}